version: '3'
services:
    
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginxproxy/certs:/etc/nginx/certs:ro
            - ./nginxproxy/vhostd:/etc/nginx/vhost.d
            - ./nginxproxy/html:/usr/share/nginx/html
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
            
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - ./nginxproxy/certs:/etc/nginx/certs:rw
            - ./nginxproxy/vhostd:/etc/nginx/vhost.d
            - ./nginxproxy/html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro    
    
    nginx:
        image: nginx:1.21.1-alpine
        expose:
            - "80"
        environment:
            VIRTUAL_HOST: areaprop.com.ar,www.areaprop.com.ar
#            LETSENCRYPT_HOST: areaprop.com.ar,www.areaprop.com.ar
            LETSENCRYPT_EMAIL: contacto@mauriciooyola.com
        volumes:
            - ./nginx/www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - nginx-proxy
            - letsencrypt
    
    php:
        image: mauriciooyola/php7.4:latest
        build: ./docker/images/php
        expose:
            - "9000"
        volumes:
            - ./nginx/www:/var/www
            - ./nginx/php/php.ini:/usr/local/etc/php/php.ini    
    mysql:
        image: linuxserver/mariadb:alpine
        tty: true
        container_name: phpdatabase
        restart: unless-stopped
        expose:
            - "3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/import:/docker-entrypoint-initdb.d
        environment:
            PUID: 1000
            PGID: 1000
            MYSQL_USER: root
            MYSQL_PASSWORD: dbpasswd
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: rootpasswd
    
    phpmyadmin:
        image: splattael/phpmyadmin:4.9.7
        container_name: phpmyadmin
        expose:
             - "80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306 
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: rootpasswd
            VIRTUAL_HOST: phpadmin.areaprop.com.ar,www.phpadmin.areaprop.com.ar
            LETSENCRYPT_HOST: phpadmin.areaprop.com.ar,www.phpadmin.areaprop.com.ar
            LETSENCRYPT_EMAIL: contacto@mauriciooyola.com

    filebrowser:
        image: hurlenko/filebrowser
        container_name: file-browser
        user: "${UID}:${GID}"
        expose:
            - "4443"
        volumes:
            - ./nginx:/data
            - ./filebrowsercfg:/config
        environment:
            FB_BASEURL: /filebrowser
            VIRTUAL_HOST: files.areaprop.com.ar,www.files.areaprop.com.ar
            LETSENCRYPT_HOST: files.areaprop.com.ar,www.files.areaprop.com.ar
            LETSENCRYPT_EMAIL: contacto@mauriciooyola.com
        restart: always
        depends_on:
            - php  
    mailserver:
        image: analogic/poste.io:2
        container_name: mailserver
        restart: unless-stopped
        ports:
            - "25:25"
            - "110:110"
            - "143:143"
            - "587:587"
            - "993:993"
            - "995:995"
            - "4190:4190"
        environment:
            - LETSENCRYPT_EMAIL=contacto@mauriciooyola.com
            - LETSENCRYPT_HOST=mail.areaprop.com.ar
            - VIRTUAL_HOST=mail.areaprop.com.ar
            - HTTPS=OFF
       volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./datamail/nginx/html/.well-known:/opt/www/.well-known
            - ./datamail/mailserver:/data
