version: '3'
services:
    
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginxproxy/certs:/etc/nginx/certs:ro
            - ./nginxproxy/vhostd:/etc/nginx/vhost.d
            - ./nginxproxy/html:/usr/share/nginx/html
        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
            
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
            - ./nginxproxy/certs:/etc/nginx/certs:rw
            - ./nginxproxy/vhostd:/etc/nginx/vhost.d
            - ./nginxproxy/html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro    
    
    nginx:
        image: nginx:latest
        expose:
            - "80"
        environment:
            VIRTUAL_HOST: areaprop.com.ar,www.areaprop.com.ar
            LETSENCRYPT_HOST: areaprop.com.ar,www.areaprop.com.ar
            LETSENCRYPT_EMAIL: contacto@mauriciooyola.com
        volumes:
            - ./nginx/www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - nginx-proxy
            - letsencrypt
    
    php:
        build: ./docker/images/php
        expose:
            - "9000"
        volumes:
            - ./nginx/www:/var/www
   
    mysql:
        image: linuxserver/mariadb:alpine
        tty: true
        container_name: phpdatabase
        restart: unless-stopped
        expose:
            - "3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/import:/docker-entrypoint-initdb.d
        environment:
            PUID: 1000
            PGID: 1000
            MYSQL_USER: root
            MYSQL_PASSWORD: dbpasswd
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: rootpasswd
    
    phpmyadmin:
        image: splattael/phpmyadmin:4.9.7
        container_name: phpmyadmin
        expose:
             - "80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306 
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: rootpasswd
            VIRTUAL_HOST: phpmyadmin.areaprop.com.ar,www.phpmyadmin.areaprop.com.ar
            LETSENCRYPT_HOST: phpmyadmin.areaprop.com.ar,www.phpmyadmin.areaprop.com.ar
            LETSENCRYPT_EMAIL: contacto@mauriciooyola.com

    filebrowser:
        image: hurlenko/filebrowser
        container_name: file-browser
        user: "${UID}:${GID}"
        expose:
            - "4443"
        volumes:
            - ./nginx:/data
            - ./filebrowsercfg:/config
        environment:
            FB_BASEURL: /filebrowser
            VIRTUAL_HOST: archivos.areaprop.com.ar,www.archivos.areaprop.com.ar
            LETSENCRYPT_HOST: archivos.areaprop.com.ar,www.archivos.areaprop.com.ar
            LETSENCRYPT_EMAIL: contacto@mauriciooyola.com
        restart: always
        depends_on:
            - php  
