version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/www:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
    php:
        image: php:7.4-fpm-alpine
        ports:
            - "9000:9000"
        volumes:
            - ./nginx/www:/var/www
    mysql:
        image: linuxserver/mariadb:alpine
        tty: true
        container_name: phpdatabase
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/import:/docker-entrypoint-initdb.d
        environment:
            PUID: 1000
            PGID: 1000
            MYSQL_USER: root
            MYSQL_PASSWORD: dbpasswd
            MYSQL_DATABASE: database
            MYSQL_ROOT_PASSWORD: rootpasswd
    
    phpmyadmin:
        image: splattael/phpmyadmin:4.9.7
        container_name: phpmyadmin
        ports:
             - "8082:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306 
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: rootpasswd

    filebrowser:
        image: hurlenko/filebrowser
        container_name: file-browser
        user: "${UID}:${GID}"
        ports:
            - 4443:8080
        volumes:
            - ./nginx:/data
            - ./filebrowsercfg:/config
        environment:
            - FB_BASEURL=/filebrowser
        restart: always
        depends_on:
            - php  
